Выполнена реализация приложения Filmorate
DmitriyDemintsev/java-filmorate pull request #3
Opened 2023-10-01 19:06 UTC by DmitriyDemintsev

созданы необходимые пакеты и классы, выполнено покрытие тестами, проверена работа API

2023-10-02 19:13 UTC, mikita95 requested changes
Все сделано хорошо. Оставил лишь небольшие замечания

2023-10-05 03:03 UTC, mikita95 approved these changes
Все отлично. Можно мержить пул-реквест

2023-10-05 03:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    static LocalDate checkData = LocalDate.of(1895, 12, 28);
private

2023-10-05 03:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmStorage filmStorage = new FilmStorage();
private final

2023-10-05 03:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static void validateFilm(@RequestBody Film film) {
этот метод незачем делать статичным и аннотация @RequestBody не нужна

2023-10-05 03:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    UserStorage userStorage = new UserStorage();
private final

2023-10-05 03:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public void validateUser(@RequestBody User user) {
private. @RequestBody в этом методе не нужна

2023-10-05 03:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public boolean equals(Object o) {
аннотация Data cсодержит уже генерацию этих методов, они здесь лишние

2023-10-05 03:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public int hashCode() {
уже есть в Data, к тому же сравнивать просто по айди неверная стратегия, бывают случаи, когда айдишник может быть нулевым и тогда это не сработает

2023-10-05 03:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public boolean equals(Object o) {
аналогично верхнему комментарию

2023-10-07 13:19 UTC, merged